spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    password: sa
    username:
    url: jdbc:h2:tcp://localhost/~/workspace/h2/data/batch
    driverClassName: org.h2.Driver
app:
  datasource:
    catalog:
      password: sa
      username:
      url: jdbc:h2:tcp://localhost/~/workspace/h2/data/batch
      driverClassName: org.h2.Driver
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
query:
  samples-count: 15